version: '1'
services:
  microservicio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@n72bzhzwyzgte7oh_tp?TNS_ADMIN=/app/oracle_wallet/
      - spring.datasource.username=REFOR3
      - spring.datasource.password=ClaseMS12345678-
    restart: always